### ISSUE TITLE
"max_entity_pair_distance" missing in glirel_beta

### ISSUE THREAD

**Issue by elya5** [jackboyla/GLiREL#13]
Hi

I've tried glirel with the spacy example. The command `nlp.add_pipe("glirel", after="ner")` fails with the following exception:

```
>>> nlp.add_pipe("glirel", after="ner")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/site-packages/spacy/language.py", line 821, in add_pipe
    pipe_component = self.create_pipe(
                     ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/spacy/language.py", line 709, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/confection/__init__.py", line 760, in resolve
    resolved, _ = cls._make(
                  ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/confection/__init__.py", line 809, in _make
    filled, _, resolved = cls._fill(
                          ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/confection/__init__.py", line 881, in _fill
    getter_result = getter(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/glirel/__init__.py", line 37, in _spacy_glirel_factory
    return SpacyGLiRELWrapper(model, batch_size=batch_size, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/glirel/spacy_integration.py", line 79, in __init__
    self.model = GLiREL.from_pretrained(pretrained_model_name_or_path, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hub_mixin.py", line 571, in from_pretrained
    instance = cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/glirel/model.py", line 674, in _from_pretrained
    model = cls(config)
            ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/glirel/model.py", line 31, in __init__
    super().__init__(config)
  File "/opt/conda/lib/python3.11/site-packages/glirel/modules/base.py", line 122, in __init__
    self.max_entity_pair_distance = config.max_entity_pair_distance
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'max_entity_pair_distance'
```

The issue seems to be that the spacy pipeline loads `glirel_beta` from huggingface which does not have `max_entity_pair_distance` in its config. It works when replacing `glirel_beta` with `glirel-large-v0`.

**Comment by jackboyla** [comment]
`pip install glirel>=1.0.1` should now throw an error if you try to load `glirel_beta` with `glirel>0.1.4` 😄

**Comment by elya5** [comment]
Thanks for the quick response! It works now :)
